/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdministrativeRole;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem.EcoSystem;
import model.Enterprise.Enterprise;
import model.Network.Network;
import model.Organization.Organization;
import model.Role.Role;
import model.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;

    public ManageUserAccountJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecosystem;
        
        cmbNetworkList.removeAllItems();
        cmbEnterprise.removeAllItems();
        cmbOrg.removeAllItems();
        cmbRoles.removeAllItems();
        
        populateNetworkCombo();

        
//        this.business = business;
//        this.container = container;
//
//        popOrganizationComboBox();
//        
//        Organization organization = (Organization) cmbEnterprise.getSelectedItem();
//        if (organization != null) {
//            populateEmployeeComboBox(organization);
//            populateRoleComboBox(organization);
//        }
//
//        popUserAccountsTable();
    }

//    public void popOrganizationComboBox() {
//        cmbEnterprise.removeAllItems();
//
//        for (Organization organization : business.getOrganizationDirectory().getOrganizationList()) {
//            cmbEnterprise.addItem(organization);
//        }
//    }
//
//    public void populateEmployeeComboBox(Organization organization) {
//        cmbOrg.removeAllItems();
//
//        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {
//            cmbOrg.addItem(employee);
//        }
//    }
//
//    private void populateRoleComboBox(Organization organization) {
//        cmbRoles.removeAllItems();
//        for (Role role : organization.getSupportedRole()) {
//            cmbRoles.addItem(role);
//        }
//    }
//
//    public void popUserAccountsTable() {
//
//        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
//
//        model.setRowCount(0);
//
//        for (Organization organization : business.getOrganizationDirectory().getOrganizationList()) {
//            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
//                Object row[] = new Object[2];
//                row[0] = ua;
//                row[1] = ua.getRole();
//                ((DefaultTableModel) tblUsers.getModel()).addRow(row);
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        grpNewUser = new javax.swing.JPanel();
        btnCreateUser = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblEmployee = new javax.swing.JLabel();
        cmbOrg = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        cmbEnterprise = new javax.swing.JComboBox();
        lblRole = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox();
        lblCreateUser = new javax.swing.JLabel();
        cmbNetworkList = new javax.swing.JComboBox();
        lblOrganizationPicker = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblUsersList = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsers);
        if (tblUsers.getColumnModel().getColumnCount() > 0) {
            tblUsers.getColumnModel().getColumn(0).setResizable(false);
            tblUsers.getColumnModel().getColumn(1).setResizable(false);
        }

        grpNewUser.setBackground(new java.awt.Color(255, 255, 255));

        btnCreateUser.setText("Create");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        lblUserName.setText("User Name:");

        lblPassword.setText("Password:");

        lblEmployee.setText("Organization:");

        cmbOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrgActionPerformed(evt);
            }
        });

        lblOrganization.setText("Enterprise:");

        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterpriseActionPerformed(evt);
            }
        });

        lblRole.setText("Role:");

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCreateUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCreateUser.setText("New User:");

        cmbNetworkList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNetworkList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkListActionPerformed(evt);
            }
        });

        lblOrganizationPicker.setText("Network:");

        javax.swing.GroupLayout grpNewUserLayout = new javax.swing.GroupLayout(grpNewUser);
        grpNewUser.setLayout(grpNewUserLayout);
        grpNewUserLayout.setHorizontalGroup(
            grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpNewUserLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(grpNewUserLayout.createSequentialGroup()
                        .addComponent(lblCreateUser)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(grpNewUserLayout.createSequentialGroup()
                        .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(grpNewUserLayout.createSequentialGroup()
                                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUserName)
                                    .addComponent(lblPassword))
                                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(grpNewUserLayout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addComponent(btnCreateUser))
                                    .addGroup(grpNewUserLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                            .addComponent(txtUserName)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, grpNewUserLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmployee)
                                    .addComponent(lblOrganization)
                                    .addComponent(lblRole))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbEnterprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(grpNewUserLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblOrganizationPicker)
                                .addGap(4, 4, 4)
                                .addComponent(cmbNetworkList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        grpNewUserLayout.setVerticalGroup(
            grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grpNewUserLayout.createSequentialGroup()
                .addComponent(lblCreateUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNetworkList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganizationPicker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganization)
                    .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployee)
                    .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grpNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateUser)
                .addGap(45, 45, 45))
        );

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Manage Users");

        lblUsersList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsersList.setText("Users List:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsersList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(19, 19, 19)))
                        .addComponent(grpNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle)
                        .addContainerGap(575, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsersList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(grpNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        String userName = txtUserName.getText();
        String password = txtPassword.getText();
        
        Network network = (Network) cmbNetworkList.getSelectedItem();
        
        if (cmbEnterprise.getSelectedItem() != null) {
            String selectedEntOption = (String) cmbEnterprise.getSelectedItem();
            String enterpriseName = selectedEntOption.replaceAll("\\s", "").split("\\|")[1];            
            Enterprise enterprise = network.getEnterpriseDirectory().getEnterpriseByName(enterpriseName);
        
            if (cmbOrg.getSelectedItem()!= null) {
                String selectedOrgOption = cmbOrg.getSelectedItem().toString();
                String orgName = selectedOrgOption.split("\\|\\s")[1];
                Organization organization = enterprise.getOrganizationDirectory().getOrganizationByName(orgName);

                if (organization != null){
                    if((!userName.equals("")) || (!userName.equals(""))){
                        if(ecoSystem.getUserAccountDirectory().userNameIsUnique(userName)){
                            Role role = (Role) cmbRoles.getSelectedItem();
                            ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, role, network, enterprise, organization);
                            JOptionPane.showMessageDialog(null, "User Account added successfully.", "Information", JOptionPane.INFORMATION_MESSAGE);
                            txtUserName.setText("");
                            txtPassword.setText("");
                            for (UserAccount ua : ecoSystem.getUserAccountDirectory().getUserAccountList()){
                                System.out.println(ua);
                            }
                                } else {                            
                                    JOptionPane.showMessageDialog(null, "Username already existed", "Warning", JOptionPane.WARNING_MESSAGE);
                                } 
                            } else {
                            JOptionPane.showMessageDialog(null, "Username & Password cannot be empty","Warning",JOptionPane.WARNING_MESSAGE);
                            }
                    } else {
                    JOptionPane.showMessageDialog(null, "Please select where you wish to add the account", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }       
        

//        popUserAccountsTable();

        
        
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterpriseActionPerformed

        populateOrgCombo();

    }//GEN-LAST:event_cmbEnterpriseActionPerformed

    private void cmbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrgActionPerformed
        // TODO add your handling code here:

        populateRoleCombo();

    }//GEN-LAST:event_cmbOrgActionPerformed

    private void cmbNetworkListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkListActionPerformed

        populateEnterpriseCombo();

    }//GEN-LAST:event_cmbNetworkListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox cmbEnterprise;
    private javax.swing.JComboBox cmbNetworkList;
    private javax.swing.JComboBox cmbOrg;
    private javax.swing.JComboBox cmbRoles;
    private javax.swing.JPanel grpNewUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateUser;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblOrganizationPicker;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUsersList;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void populateNetworkCombo() {
    
        cmbNetworkList.removeAllItems();

        if (!ecoSystem.getNetworkList().isEmpty()){
            for (Network n : ecoSystem.getNetworkList()){
                cmbNetworkList.addItem(n);
            }
        }
    }

    private void populateEnterpriseCombo() {
        
        cmbEnterprise.removeAllItems();
        
        Network network = (Network) cmbNetworkList.getSelectedItem();
        
        if (network != null ){
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
                cmbEnterprise.addItem(e.getType() + " | " + e);
            }
        }
    }

    private void populateOrgCombo() {
        
        cmbOrg.removeAllItems();
        
        Network network = (Network) cmbNetworkList.getSelectedItem();
                
        if (cmbEnterprise.getSelectedItem() != null) {
            String selectedOption = (String) cmbEnterprise.getSelectedItem();
            String enterpriseName = selectedOption.replaceAll("\\s", "").split("\\|")[1];            
            Enterprise enterprise = network.getEnterpriseDirectory().getEnterpriseByName(enterpriseName);
            
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                cmbOrg.addItem(o.getType() + " | " + o);
            }
            
            
//            String type = enterprise.getType().getValue();
//            
//            switch (type) {
//                case "Animal Shelter":
//                    cmbOrg.removeAllItems();
//                    for (Organization.Type organizationType : Organization.Type.values()){
//                        if (organizationType.getValue().equals("Animal Register Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                        if (organizationType.getValue().equals("Animal Management Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                    }
//                    break;
//                case "Medical Care":
//                    cmbOrg.removeAllItems();
//                    for (Organization.Type organizationType : Organization.Type.values()){
//                        if (organizationType.getValue().equals("Vet Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                        if (organizationType.getValue().equals("Treatment Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                    }
//                    break;   
//                case "Adoption":
//                    cmbOrg.removeAllItems();
//                    for (Organization.Type organizationType : Organization.Type.values()){
//                        if (organizationType.getValue().equals("Adopter Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                        if (organizationType.getValue().equals("Adoption Operation Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                    }
//                    break;
//                case "Volunteer":
//                    cmbOrg.removeAllItems();
//                    for (Organization.Type organizationType : Organization.Type.values()){
//                        if (organizationType.getValue().equals("Volunteer Management Organization")) {
//                            cmbOrg.addItem(organizationType);      
//                        }
//                        if (organizationType.getValue().equals("Volunteer Organization")){
//                            cmbOrg.addItem(organizationType);      
//                        }
//                    }
//                    break;    
//                default:
//                    cmbOrg.removeAllItems();
//            }
        }
        
    }

    private void populateRoleCombo() {

        cmbRoles.removeAllItems();
        
        Network network = (Network) cmbNetworkList.getSelectedItem();
        
        if (cmbEnterprise.getSelectedItem() != null) {
            String selectedEntOption = (String) cmbEnterprise.getSelectedItem();
            String enterpriseName = selectedEntOption.replaceAll("\\s", "").split("\\|")[1];            
            Enterprise enterprise = network.getEnterpriseDirectory().getEnterpriseByName(enterpriseName);
        
            if (cmbOrg.getSelectedItem()!= null) {
                String selectedOrgOption = cmbOrg.getSelectedItem().toString();
                String orgName = selectedOrgOption.split("\\|\\s")[1];
                Organization organization = enterprise.getOrganizationDirectory().getOrganizationByName(orgName);

                for (Role role : organization.getSupportedRole()) {
                    cmbRoles.addItem(role);
                }
                
                
                
//                
//                String orgType = selectedOrgOption.split("\\|")[0];
//
//                switch (orgType) {
//                    case "Animal Register Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Animal Register")){
//                                cmbRoles.addItem(roleType);      
//                            }                           
//                        }
//                        break;
//                    case "Animal Management Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Animal Manager")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//                    case "Vet Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Vet")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//                    case "Treatment Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Pharmacist")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                            if (roleType.getValue().equals("Behavior Therapist")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//                    case "Adopter Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Adopter")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//                    case "Adoption Operation Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Adoption Manager")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//                    case "Volunteer Management Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Volunteer Manager")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//                    case "Volunteer Organization ":
//                        for (Role.RoleType roleType : Role.RoleType.values()){
//                            if (roleType.getValue().equals("Volunteer")){
//                                cmbRoles.addItem(roleType);      
//                            }
//                        }
//                        break;
//
//                    default:
//                        cmbRoles.removeAllItems();
//                }
            }
        }
    }
}
